config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
	
	get 'questions/show'
	get 'questions/manage'
	get 'questions/ban'
	post 'questions/like'
	get 'questions/like'
	post'questions/ban'
	get 'questions/ban'
	post'questions/search'
	get 'questions/search'
	post'questions/addquestion'
	post 'questions/addanswer'
	
	get 'answers/reply'
	post 'answers/like'
	get 'answers/like'
	post 'answers/reply'
	get 'answers/reply'
	post'answers/reply'
	
	post 'articles/upload'
	post 'articles/download'
	get 'articles/download'
	
  get  'signup' => 'users#new'
  get 'users/information'
	post 'users/search'
	get 'users/search'
  
  resources :articles
  resources :likes
  resources :fields
  resources :answers
  resources :questions
  resources :users

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :question
    belongs_to :answer
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: [:show, :edit, :update, :destroy]

  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1
  # PATCH/PUT /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: 'Like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def like_params
      params.require(:like).permit(:liketype, :likeid, :useremail)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :liketype %><br>
    <%= f.text_field :liketype %>
  </div>
  <div class="field">
    <%= f.label :likeid %><br>
    <%= f.number_field :likeid %>
  </div>
  <div class="field">
    <%= f.label :useremail %><br>
    <%= f.text_field :useremail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Likes</h1>

<table>
  <thead>
    <tr>
      <th>Liketype</th>
      <th>Likeid</th>
      <th>Useremail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.liketype %></td>
        <td><%= like.likeid %></td>
        <td><%= like.useremail %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Liketype:</strong>
  <%= @like.liketype %>
</p>

<p>
  <strong>Likeid:</strong>
  <%= @like.likeid %>
</p>

<p>
  <strong>Useremail:</strong>
  <%= @like.useremail %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>