config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'sessions/new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
	
	get 'questions/show'
	get 'questions/manage'
	get 'questions/ban'
	post 'questions/like'
	get 'questions/like'
	post'questions/ban'
	get 'questions/ban'
	post'questions/search'
	get 'questions/search'
	post'questions/addquestion'
	post 'questions/addanswer'
	
	get 'answers/reply'
	post 'answers/like'
	get 'answers/like'
	post 'answers/reply'
	get 'answers/reply'
	post'answers/reply'
	
	post 'articles/upload'
	post 'articles/download'
	get 'articles/download'
	
  get  'signup' => 'users#new'
  get 'users/information'
	post 'users/search'
	get 'users/search'
  
  resources :articles
  resources :likes
  resources :fields
  resources :answers
  resources :questions
  resources :users

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    has_many :likes
    belongs_to :question
    belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end
  def like
    @aid = params[:aid]
    @uid = session[:user_id]
    @qid = session[:qid]
    @question=Question.find(@qid)
    @exist=Like.where(:user_id => @uid).where(:answer_id=>@aid).count
    if(@exist==0) then
    @new_like=Like.create(:answer_id =>@aid,:user_id =>@uid)
    else
    @lid=Like.where(:user_id => @uid).where(:answer_id => @aid).first.id
    Like.delete(@lid)
    end  
    @answers=Answer.where(:question_id => @qid).order("level")
    redirect_to '/questions/show?qid='+@qid
  end
  def reply
   @alevel=params[:alevel]
   @qid=session[:qid]
   if(@qid!=nil) then
     @question=Question.find(@qid)
     @answers=Answer.where(:question_id => @qid).order("level")
   else
     puts "nil"
   end
  end
  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:questionid, :level, :title, :content, :answeruser, :filepath, :liker, :obligate1, :obligate2, :obligate3)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :questionid %><br>
    <%= f.number_field :questionid %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :answeruser %><br>
    <%= f.text_field :answeruser %>
  </div>
  <div class="field">
    <%= f.label :filepath %><br>
    <%= f.text_field :filepath %>
  </div>
  <div class="field">
    <%= f.label :liker %><br>
    <%= f.text_field :liker %>
  </div>
  <div class="field">
    <%= f.label :obligate1 %><br>
    <%= f.text_field :obligate1 %>
  </div>
  <div class="field">
    <%= f.label :obligate2 %><br>
    <%= f.text_field :obligate2 %>
  </div>
  <div class="field">
    <%= f.label :obligate3 %><br>
    <%= f.text_field :obligate3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Questionid</th>
      <th>Level</th>
      <th>Title</th>
      <th>Content</th>
      <th>Answeruser</th>
      <th>Filepath</th>
      <th>Liker</th>
      <th>Obligate1</th>
      <th>Obligate2</th>
      <th>Obligate3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.questionid %></td>
        <td><%= answer.level %></td>
        <td><%= answer.title %></td>
        <td><%= answer.content %></td>
        <td><%= answer.answeruser %></td>
        <td><%= answer.filepath %></td>
        <td><%= answer.liker %></td>
        <td><%= answer.obligate1 %></td>
        <td><%= answer.obligate2 %></td>
        <td><%= answer.obligate3 %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/like.html.erb
<p id="notice"><%= notice %></p>
<p><%=@id%></p>
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Questionuser:</strong>
  <%= @question.questionuser %>
</p>

<p>
  <strong>Articleid:</strong>
  <%= @question.article_id %>
</p>

<p>
  <strong>Field:</strong>
  <%= @question.field %>
</p>

<p>
  <strong>Liker:</strong>
  <%= @question.likes.count %>
</p>
<h2><p>Answers</p></h2>
<table align="center" width=1000px >
  <% @answers.each do |answer| %>
  <thead>
    <tr>
      <th align="left">level:<%=answer.level %><br>Time<%= answer.created_at %></th>
      <th align="left">Answeruser</th>
      <th align="right">like:<%=answer.likes.count%></th>
      <th align="center"><%=button_to "reply",{:controller =>"answers",:action =>"reply",:alevel =>answer.level}%></th>
    </tr>
  </thead>
  
  <tbody>
       <tr>
         <td></td>
         <td><%= answer.answeruser %></td>
         <td><%= answer.content %></td>
         <%if(Like.where(:user_id=>session[:user_id]).where(:answer_id => answer.id).count==0)%>
         <td align="right"><%=button_to "like it!",{:controller =>"answers",:action => "like",:aid =>answer.id}%></td>
         <%else%>
         <td align="right"><%=button_to "cancel like!!",{:controller =>"answers",:action => "like",:aid =>answer.id}%></td>
         <%end%>
       </tr>
  </tbody>
  <% end %>
</table>
<br>
<hr>
<%if(@question.state==1)%>
<h1>The Question is banned by the owner!<h1>
<%else%>  
<h1><label>您有什么看法？</label><h1>
  <%if(Like.where(:user_id=>session[:user_id]).where(:question_id => session[:qid]).count==0)%>
      <p align="right"><%=button_to "like this question!",{:controller =>"questions",:action => "like"}%></p>
  <%else%>
      <p align="right"><%=button_to "cancel like this question!!",{:controller =>"questions",:action => "like"}%></p>
  <%end%>
<%=form_tag  :controller => "questions",:action => "addanswer",:method => :post do%>
<p>
<%=text_area_tag :content,params[:content],:innerText =>"sads",:style =>"width:400px;height:200px;" %>
</p>
<%=submit_tag "submit" %>
<% end %>
<% end %>
<p>
<%= link_to 'Back', questions_path %>
</p>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/reply.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>Questionuser:</strong>
  <%= @question.questionuser %>
</p>

<p>
  <strong>Articleid:</strong>
  <%= @question.article_id %>
</p>

<p>
  <strong>Field:</strong>
  <%= @question.field %>
</p>

<p>
  <strong>Liker:</strong>
  <%= @question.liker %>
</p>
<h2><p>Answers</p></h2>
<table align="center" width=1000px >
  <% @answers.each do |answer| %>
  <thead>
    <tr>
      <th align="left">level:<%=answer.level %><br>Time<%= answer.created_at %></th>
      <th align="left">Answeruser</th>
      <th align="right">like:</th>
      <th align="center"><%=button_to "reply",{:controller =>"answers",:action =>"reply",:alevel =>answer.level}%></th>
    </tr>
  </thead>
  
  <tbody>
       <tr>
         <td></td>
         <td><%= answer.answeruser %></td>
         <td><%= answer.content %></td>
         <%if(Like.where(:user_id=>session[:user_id]).where(:answer_id => answer.id).count==0)%>
         <td align="right"><%=button_to "like it!",{:controller =>"answers",:action => "like",:aid =>answer.id}%></td>
         <%else%>
         <td align="right"><%=button_to "cancel like!!",{:controller =>"answers",:action => "like",:aid =>answer.id}%></td>
         <%end%>
       </tr>
  </tbody>
  <% end %>
</table>
<br>
<hr>
<%if(@question.state==1)%>
<h1>The Question is banned by the owner!<h1>
<%else%>  
<h1><label>您有什么看法？</label><h1>
<%if(Like.where(:user_id=>session[:user_id]).where(:question_id => session[:qid]).count==0)%>
      <p align="right"><%=button_to "like this question!",{:controller =>"questions",:action => "like"}%></p>
<%else%>
      <p align="right"><%=button_to "cancel like this question!!",{:controller =>"questions",:action => "like"}%></p>
<%end%>
reply to level <%=@alevel%>:
<%=form_tag  :controller =>"questions",:action => "addanswer",:method => :post do%>
<p>
<%=text_area_tag :content,params[:content],:autofocus =>"true",:placeholder =>"reply to level "+@alevel+":",:style=>"width:400px;height:200px" %>
</p>
<%=submit_tag "submit" %>
<% end %>
<% end %>
<p>
<%= link_to 'Back to the main page', questions_path %>
</p>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Questionid:</strong>
  <%= @answer.questionid %>
</p>

<p>
  <strong>Level:</strong>
  <%= @answer.level %>
</p>

<p>
  <strong>Title:</strong>
  <%= @answer.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>Answeruser:</strong>
  <%= @answer.answeruser %>
</p>

<p>
  <strong>Filepath:</strong>
  <%= @answer.filepath %>
</p>

<p>
  <strong>Liker:</strong>
  <%= @answer.liker %>
</p>

<p>
  <strong>Obligate1:</strong>
  <%= @answer.obligate1 %>
</p>

<p>
  <strong>Obligate2:</strong>
  <%= @answer.obligate2 %>
</p>

<p>
  <strong>Obligate3:</strong>
  <%= @answer.obligate3 %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>